### ISSUE TITLE
Damped follower

### ISSUE THREAD

**Issue by 958479612** [IzaZed/UPBGE-Templates#1]
Demand new case. Constraint: damp following. Make the fixed point light always shine on the active target
![aass](https://user-images.githubusercontent.com/82086788/122628246-a50c4680-d0e7-11eb-92f7-6a070cef7ec8.png)

**Comment by AquariusPower** [comment]
I dont understand the text on the screenshot, but I guess this is an improvement request right? may be you could fork and patch it?
